"""Rename auth0_id to google_id

Revision ID: 73f69229d06a
Revises: 498f0c7d5ddb
Create Date: 2026-05-06 21:19:24.516738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f69229d06a'
down_revision: Union[str, Sequence[str], None] = '498f0c7d5ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'auth0_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth0_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
