"""create_user_recommendations_table

Revision ID: b63920fcde2a
Revises: 11ac57abc776
Create Date: 2026-05-19 20:08:15.911956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63920fcde2a'
down_revision: Union[str, Sequence[str], None] = '11ac57abc776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_recommendations_id'), 'user_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_user_recommendations_user_id'), 'user_recommendations', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_recommendations_user_id'), table_name='user_recommendations')
    op.drop_index(op.f('ix_user_recommendations_id'), table_name='user_recommendations')
    op.drop_table('user_recommendations')
    # ### end Alembic commands ###
