"""remove language setting

Revision ID: cce93738dda4
Revises: 9075d8504009
Create Date: 2026-06-04 22:49:42.393039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce93738dda4'
down_revision: Union[str, Sequence[str], None] = '9075d8504009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
