"""replace notes with exercises json in workouts

Revision ID: f3f18106b2f8
Revises: cce93738dda4
Create Date: 2026-06-12 23:35:05.189793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f18106b2f8'
down_revision: Union[str, Sequence[str], None] = 'cce93738dda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('exercises', sa.JSON(), nullable=True))
    op.drop_column('workouts', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('workouts', 'exercises')
    # ### end Alembic commands ###
