[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "53faa5f93e406bc929f0bfaa704815eb2f6ae8606286ec86f7e11128195ae40d"

[auth.google]
client_id = "1079175312354-rh5qlv2h3dlofrdr4kva1s5seud8hor9.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration" 